### ISSUE TITLE
The Example provided in README.md needs a fix

### ISSUE THREAD

**Issue by shashankshet** [IBM/python-json-log-formatter#5]
Hello team,

I was going through this repo and trying to use this logging module, while trying it out I observed that the example provided in README.md file needs a minor change
Provided example in README.md  is as given below:
```
from python_logger import PythonLogger
import logging

VERSION = "1.0.0 (2022/11/24)"
PythonLogger.setup_logger(VERSION)

LOGGER = logging.getLogger(__name__)
```

The expected code:

```
from python_json_log_formatter import PythonLogger
import logging

VERSION = "1.0.0 (2022/11/24)"
PythonLogger.setup_logger(VERSION)

LOGGER = logging.getLogger(__name__)
```

only a small change in first line during import

**Comment by NielsKorschinsky** [comment]
Hi @shashankshet ,
thanks for your contribution.
What kind of log engine are you using?

Please check PR https://github.com/IBM/python-json-log-formatter/pull/6 whether this matches your expectation.

**Comment by shashankshet** [comment]
Yeah, this looks good.
I am using the python default logging module

**Comment by NielsKorschinsky** [comment]
Thanks for your feedback!
